### ISSUE TITLE
Update axios dependency to fix security vulnerability

### ISSUE THREAD

**Issue by FM-96** [ilovepdf/ilovepdf-nodejs#1]
One of your dependencies, axios, contains a Server-Side Request Forgery vulnerability. You should upgrade it to version 0.21.1 or higher. (The version in your current dependencies is 0.19.2.)

See here for details: https://npmjs.com/advisories/1594

**Comment by diego-ilovepdf** [comment]
Hi! Thank you for advise us. Dependecy is updated now 👍
