### ISSUE TITLE
Using in browser

### ISSUE THREAD

**Issue by gee666** [ilovepdf/ilovepdf-nodejs#11]
It's more a question than an issue
How to use it in browser on client side? I want to compress pdf before uploading to server. I only see two ways to add file: with FILE_PATH and with FILE_URL, how can I add a file which user is trying to upload to the browser? 
Thank you for the answer

**Comment by diego-ilovepdf** [comment]
Hi @gee666 !,

In order to use it on client side we have a different library that you can find [here](https://github.com/ilovepdf/ilovepdf-js). Also you have there two examples using the ILovePDFFile class and public URLs 👍 .
