### ISSUE TITLE
Incorrect types, missing webhook information and automatically position sign field

### ISSUE THREAD

**Issue by nealoke** [ilovepdf/ilovepdf-nodejs#13]
Hi,

Thanks for fixing the issue regarding the signature, a few questions/remarks in regards to signing:

- The types for the language are not what is mentioned in the docs (currently only  "EN" | "ES" | "FR" | "IT" | "JA" | "ZH-CN" | "ZH-TW" | "BG" are valid, while NL is mentioned in the docs as well as a bunch of other ones)

- Is it possible to see what we get in terms of webhook data? Currently I need to use purchased credits just to see what I will be getting as webhooks which is unfortunate...

- Is it anyway possible to set the position of the sign field to the bottom right of the last page? If so, how or what are the coordinates?

**Comment by guillem-pdf** [comment]
Hi,

> The types for the language are not what is mentioned in the docs (currently only "EN" | "ES" | "FR" | "IT" | "JA" | "ZH-CN" | "ZH-TW" | "BG" are valid, while NL is mentioned in the docs as well as a bunch of other ones)

New version ( 0.2.3 ) of the library @ilovepdf/ilovepdf-nodejs was updated with the types according the documentation. Thank you for providing the bug.

> Is it possible to see what we get in terms of webhook data? Currently I need to use purchased credits just to see what I will be getting as webhooks which is unfortunate...

You are right, we will update the frontend with examples of the webhook data delivered. In any case, if you need an account for testing / implementing / adapting your solution, please [contact us ](https://developer.ilovepdf.com/contact) so we can give you a package for you to do that without charge.

> Is it anyway possible to set the position of the sign field to the bottom right of the last page? If so, how or what are the coordinates?

This is not yet possible, although, it is something that we are going to implement in the upcoming future. I can evaluate the difficulty of this feature and get you an approximate date that we can deploy this.

Meanwhile, the coordinates are defined on a PDF as: One point is defined as 1/72 of an inch (2,54 cm). An A4 type of page (mostly common PDF size) is 595x842. If you want to place it on the "bottom right", you should then use the coordinates "500" and "-700" for that (considering an A4 document and the size of the signature is 40). Which should look like the attached image:

![image (1)](https://github.com/ilovepdf/ilovepdf-nodejs/assets/80250668/983373be-4898-4c2a-8b7c-5f1eb56cc378)

**Comment by nealoke** [comment]
@guillem-pdf thanks for the reply, any update on when we could specify the last page for signature? I can only believe that others using this service are also in need of this functionality. I have yet to see a contract where you sign on the first page in stead of the last 😅.

**Comment by nealoke** [comment]
Too bad you closed this ticket without providing an answer. As a developer and SaaS I think this isn't a great library to work with. Some persistent issues and missing essential features... 😓

**Comment by diego-ilovepdf** [comment]
Hi @nealoke !

Sorry for the inconvenience. We had an error tracking this issue but we are currently working on it.

For the moment, I will reopen it and we will reply when the fix is released.

Diego.

**Comment by guillem-pdf** [comment]
Hi @nealoke sorry about the delay.

We are currently working on a fix, there is a way, after each upload to send a parameter that returns the info about the PDF (each page size and the page count of all of the pdf).

That being said, to do that, we have to update all of the SDKs to add that parameter, and so the website.

I already put that into our schedule, so we can deliver this feature ASAP. Once finished, I'll let you know.
