### ISSUE TITLE
cannot sign

### ISSUE THREAD

**Issue by hahan1401** [ilovepdf/ilovepdf-nodejs#17]
![Untitled](https://github.com/ilovepdf/ilovepdf-nodejs/assets/147976365/a28e67f2-f10c-4007-a0b0-7cb8cb19a061)

i got this error when trying to go to sign url

**Comment by guillem-pdf** [comment]
@hahan1401 I'll give it a look as soon as possible, thank you for reporting this issue.

**Comment by guillem-pdf** [comment]
Hi @hahan1401 , did you remove the api key that you used to create the signature?

**Comment by hahan1401** [comment]
@guillem-pdf, i am not sure, i'll check it. tks for ur reply.

**Comment by hahan1401** [comment]
sr @guillem-pdf, i fugured it out, this request was created by a deleted app. but there is a new problem, although the app is deleted, all requests was created by this app is still being at 'sent' status, that cause to my email get remined every day, that is siriously anoying, but i cannot void those requests because i do not have the keys anymore.

**Comment by guillem-pdf** [comment]
Hi @hahan1401 we can figure something out, please, use the following contact form [https://developer.ilovepdf.com/contact](https://developer.ilovepdf.com/contact) to either try to restablish your keys or that we can manually void your ongoing signatures.

I'm going to close this ticket for now.

**Comment by hahan1401** [comment]
@diego-ilovepdf, i just have sent a contact, pls check it and help me
