### ISSUE TITLE
File size error in upload task

### ISSUE THREAD

**Issue by juanludlf** [ilovepdf/ilovepdf-nodejs#2]
Hi,

I'm trying to repair a PDF but the upload task throws the following error:

`Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`

The file size is 30 MB. Axios default `maxBodyLength` is 10mb I think. Is this an intended API limit or just a config issue?

Thanks

**Comment by diego-ilovepdf** [comment]
Hi! It was a problem with axios and our configuration. Now the limit is set to Infinity ( and axios can detect it! )
