### ISSUE TITLE
Error module ILovePDFFile

### ISSUE THREAD

**Issue by vini-lima** [ilovepdf/ilovepdf-nodejs#3]
Hi!

I dont use module ILovePDFFile, node cannot find module.

const ILovePDFFile = require('@ilovepdf/ilovepdf-nodejs/ILovePDFFile');

Error: Cannot find module '@ilovepdf/ilovepdf-nodejs/ILovePDFFile'

I have other problem with ILovePdfApi:

const instance = ILovePDFApi(process.env.PUBLIC_KEY, process.env.SECRET_KEY);
                 ^

TypeError: ILovePDFApi is not a constructor

**Comment by diego-ilovepdf** [comment]
Hi @vini-lima,

The problems are related to wrong paths:

```
const { default: ILovePDFApi } = require("@ilovepdf/ilovepdf-nodejs");
const { default: ILovePDFFile } = require("@ilovepdf/ilovepdf-js-core/utils/ILovePDFFile");

const api = new ILovePDFApi( 'public_key', 'secret_key' );

const file = new ILovePDFFile( '/path/to/file' );
```

**Comment by corentinclichy** [comment]
But what do I need to do if I use import instead of required.

I have the same issue

**Comment by diego-ilovepdf** [comment]
Hi @corentinclichy ! If you are using ESM instead of CJS to import your dependencies don't worry, we support both. For example, you can import the packages as:

```ts
import ILovePDFApi from '@ilovepdf/ilovepdf-nodejs'
import ILovePDFFile from '@ilovepdf/ilovepdf-nodejs/ILovePDFFile.js'
```

Cheers.
