### ISSUE TITLE
Sign pdf

### ISSUE THREAD

**Issue by LucBerge** [ilovepdf/ilovepdf-nodejs#4]
Hello,
It is possible to sign a pdf using the [web interface](https://www.ilovepdf.com/sign-pdf).
Will it be possible to do it with the API soon ?

**Comment by guillem-pdf** [comment]
Hello @LucBerge ,

Thank you for your interest in our products

1. Yes, you can sign PDF through our web interface, 
2. The API will be released on the first weekend of April, you can check it out on our website:  [https://developer.ilovepdf.com/](https://developer.ilovepdf.com/)

**Comment by LucBerge** [comment]
Great ! See you april then

**Comment by LucBerge** [comment]
Hey, thanks for the update. I can see in this file than the signature must be a url to a file.

What kind of format are supported ?
Is there a way to use a file without having to uploading it somewhere ?

Signatures are sensitive informations. If I can avoid uploading it, it's would be better.

**Comment by guillem-pdf** [comment]
Thanks for your interest in our product.

To answer your questions:

> What kind of format are supported ?

Only PDF format is supported.

> Is there a way to use a file without having to uploading it somewhere ?

Sure, we added a [new example](https://github.com/ilovepdf/ilovepdf-nodejs/blob/master/src/samples/sign_file.ts) on how you can actually upload a file instead of using a URL to upload the file.

It is very important to update to version 0.2.1 of @ilovepdf/ilovepdf-nodejs before proceeding.

Let us know if this helps you solve your issues.

If you need more technical or sales support (we can provide you with some starting credits to start your development with our signature product, for instance), use the [following link](https://developer.ilovepdf.com/contact).

**Comment by LucBerge** [comment]
Thank you @guillem-pdf for the new example.

One more thing : On the UI, we can sign a pdf by importing a signature file. Is it possible to do it with the API ? How ?

**Comment by guillem-pdf** [comment]
Hello @LucBerge 

The API does not allow you to sign directly a document, it is meant to sent documents to be signed by others.

If you want, you can force the signer to use the parameter **force_signature_type ** (check the [documentation](https://developer.ilovepdf.com/docs/api-reference#create-signature) ), and in this case, force the signer to use either an image or sign, depending on your needs.

Brand logo is only to set the logo and the email of your company for the initial email.

Let me know if this was helpful.

**Comment by LucBerge** [comment]
Hello @guillem-pdf 

I'm not able to run the simple-signe example : https://github.com/ilovepdf/ilovepdf-nodejs/blob/master/src/samples/sign_file.ts

I got the following error on `.start()`

```
    data: {
      error: {
        type: 'StartError',
        message: "The task can't be initialized, check why in the params",
        code: 400,
        param: {
          task: [ 'You don\\t have enough signatures to start a request.' ]
        }
      }
    }
```

Do you have an idea why ?

**Comment by diego-ilovepdf** [comment]
Hi @LucBerge !

In order to sign the file you need to have a subscription or e-signatures packages in your account. You can check our prices at [iLovePDF Developer](https://developer.ilovepdf.com/pricing).

**Comment by guillem-pdf** [comment]
Hi @LucBerge ,

If you are interested in using our signature product, you can also use our [contact form](https://developer.ilovepdf.com/contact) to speak with our sales team in case you need some free credits to test the tool.

Kind regards,

Guillem
